export enum FLOWS {
  AUTH_FLOW = 'AUTH_FLOW',
  MAIN_FLOW = 'PRODUCT_FLOW',
}

export enum AUTH_SCREENS {
  LOGIN = 'LOGIN',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
}

export enum MAIN_SCREENS {
  MAIN_PAGE = 'MAIN_PAGE',
}
